In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Load integrated data from week 2

sales = pd.read_csv("/content/sales_integrated.csv")

print("Sales shape:", sales.shape)

display(sales.head())

Sales shape: (130402, 55)

,so_id,line_number,product_id,quantity,unit_price,gst_rate,line_total,gst_amount,line_grand_total,customer_id,branch_id,order_date,delivery_date,order_status,payment_terms,total_order_value,total_gst_amount,grand_total,sales_channel,product_name,category,machine_type,brand,model_compatibility,unit_cost,unit_price_product,margin_percentage,gst_rate_product,weight_kg,dimensions_cm,material_type,warranty_months,reorder_level,safety_stock,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date,customer_type,industry_segment,city,state,pincode,region,branch_id_customer,credit_limit,current_balance,payment_terms_customer,customer_since,last_purchase_date_customer,total_purchase_value,customer_rating
0,SO-990591,1,P018,19,11300,28,214700,60116.0,274816.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Wheel Rim WR-24,Undercarriage,Bulldozer,CAT,CAT D6R,8200,11300,37.8,28,24.00,70x25x25,steel,12,12,6,30,20,High,Medium,piece,8000,2024-02-20,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3
1,SO-990591,2,P026,2,310,18,620,111.6,731.6,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3
2,SO-990591,3,P026,3,310,18,930,167.4,1097.4,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3
3,SO-990591,4,P013,9,1450,18,13050,2349.0,15399.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Seal Kit SK-15,Seals,Excavator,CAT,CAT 320D,950,1450,52.6,18,0.60,15x10x6,rubber,6,80,40,200,9,Medium,High,set,920,2022-12-19,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3
4,SO-990591,5,P004,3,39800,28,119400,33432.0,152832.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Track Chain TC-45,Undercarriage,Bulldozer,Volvo,Volvo D6,32500,39800,22.5,28,210.00,180x40x35,steel,18,8,4,20,30,High,Low,set,32000,2020-06-18,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3

In [2]:
# Inspect Sales Dataset
print("Columns:")
print(sales.columns.tolist())

print("\nData types:")
print(sales.dtypes)

print("\nMissing values:")
display(
    sales.isnull().sum()
    .sort_values(ascending=False)
    .head(20)
)

Columns:
['so_id', 'line_number', 'product_id', 'quantity', 'unit_price', 'gst_rate', 'line_total', 'gst_amount', 'line_grand_total', 'customer_id', 'branch_id', 'order_date', 'delivery_date', 'order_status', 'payment_terms', 'total_order_value', 'total_gst_amount', 'grand_total', 'sales_channel', 'product_name', 'category', 'machine_type', 'brand', 'model_compatibility', 'unit_cost', 'unit_price_product', 'margin_percentage', 'gst_rate_product', 'weight_kg', 'dimensions_cm', 'material_type', 'warranty_months', 'reorder_level', 'safety_stock', 'max_stock_level', 'lead_time_days', 'criticality_level', 'usage_frequency', 'uom', 'last_purchase_price', 'last_purchase_date', 'customer_type', 'industry_segment', 'city', 'state', 'pincode', 'region', 'branch_id_customer', 'credit_limit', 'current_balance', 'payment_terms_customer', 'customer_since', 'last_purchase_date_customer', 'total_purchase_value', 'customer_rating']

Data types:
so_id                           object
line_number                      int64
product_id                      object
quantity                         int64
unit_price                       int64
gst_rate                         int64
line_total                       int64
gst_amount                     float64
line_grand_total               float64
customer_id                     object
branch_id                       object
order_date                      object
delivery_date                   object
order_status                    object
payment_terms                   object
total_order_value                int64
total_gst_amount               float64
grand_total                    float64
sales_channel                   object
product_name                    object
category                        object
machine_type                    object
brand                           object
model_compatibility             object
unit_cost                        int64
unit_price_product               int64
margin_percentage              float64
gst_rate_product                 int64
weight_kg                      float64
dimensions_cm                   object
material_type                   object
warranty_months                  int64
reorder_level                    int64
safety_stock                     int64
max_stock_level                  int64
lead_time_days                   int64
criticality_level               object
usage_frequency                 object
uom                             object
last_purchase_price              int64
last_purchase_date              object
customer_type                   object
industry_segment                object
city                            object
state                           object
pincode                          int64
region                          object
branch_id_customer              object
credit_limit                     int64
current_balance                  int64
payment_terms_customer          object
customer_since                  object
last_purchase_date_customer     object
total_purchase_value             int64
customer_rating                  int64
dtype: object

Missing values:

so_id                0
line_number          0
product_id           0
quantity             0
unit_price           0
gst_rate             0
line_total           0
gst_amount           0
line_grand_total     0
customer_id          0
branch_id            0
order_date           0
delivery_date        0
order_status         0
payment_terms        0
total_order_value    0
total_gst_amount     0
grand_total          0
sales_channel        0
product_name         0
dtype: int64

In [3]:
# Create a Working Copy
# Not modifying the original integrated dataset directly.
sales_fe = sales.copy()

print("Feature engineering dataset shape:", sales_fe.shape)

Feature engineering dataset shape: (130402, 55)

### **1. Date Features**

In [4]:
# Convert Order Date
sales_fe['order_date'] = pd.to_datetime(
    sales_fe['order_date'],
    errors='coerce'
)

print(
    "Invalid order dates:",
    sales_fe['order_date'].isna().sum()
)

Invalid order dates: 0

###  **Create Date Features**

In [6]:
sales_fe['order_year'] = (
    sales_fe['order_date'].dt.year
)

sales_fe['order_month'] = (
    sales_fe['order_date'].dt.month
)

sales_fe['order_month_name'] = (
    sales_fe['order_date'].dt.month_name()
)

sales_fe['order_quarter'] = (
    sales_fe['order_date'].dt.quarter
)

sales_fe['order_week'] = (
    sales_fe['order_date'].dt.isocalendar().week
)

sales_fe['order_day'] = (
    sales_fe['order_date'].dt.day
)

sales_fe['order_day_name'] = (
    sales_fe['order_date'].dt.day_name()
)

sales_fe['order_day_of_week'] = (
    sales_fe['order_date'].dt.dayofweek
)

# Check
display(
    sales_fe[
        [
            'order_date',
            'order_year',
            'order_month',
            'order_month_name',
            'order_quarter',
            'order_day_name'
        ]
    ].head()
)

,order_date,order_year,order_month,order_month_name,order_quarter,order_day_name
0,2022-05-24,2022,5,May,2,Tuesday
1,2022-05-24,2022,5,May,2,Tuesday
2,2022-05-24,2022,5,May,2,Tuesday
3,2022-05-24,2022,5,May,2,Tuesday
4,2022-05-24,2022,5,May,2,Tuesday

### **2. Sales Line Features**

In [8]:
# Sales Calculation
sales_fe['calculated_line_total'] = (
    sales_fe['quantity']
    * sales_fe['unit_price']
)

# Calculate the difference from the existing value:
if 'line_total' in sales_fe.columns:

    sales_fe['line_total_difference'] = (
        sales_fe['line_total']
        - sales_fe['calculated_line_total']
    )

    print(
        "Maximum line total difference:",
        sales_fe['line_total_difference'].abs().max()
    )

Maximum line total difference: 0

### **3. Unit Price and Quantity Features**

In [10]:
sales_fe['quantity_log'] = np.log1p(
    sales_fe['quantity']
)

sales_fe['unit_price_log'] = np.log1p(
    sales_fe['unit_price']
)

# These transformed features can be useful later for modelling because sales quantities and prices may be highly skewed.

### **4. Order-Level Features**
Sales Lines contain multiple rows for the same so_id.

Therefore, order-level features should be calculated at the order level rather than treating every line as a separate order.

In [11]:
order_summary = (
    sales_fe
    .groupby('so_id')
    .agg(
        order_quantity=('quantity', 'sum'),
        order_line_count=('so_id', 'size'),
        order_sales_value=('line_grand_total', 'sum'),
        unique_products=('product_id', 'nunique')
    )
    .reset_index()
)

display(order_summary.head())

,so_id,order_quantity,order_line_count,order_sales_value,unique_products
0,SO-100070,17,2,292352.0,2
1,SO-100088,132,10,2770123.8,9
2,SO-100155,108,9,1564183.0,7
3,SO-100192,36,2,264196.0,2
4,SO-100220,21,3,168070.8,3

### **Merge Order-Level Features Back**

In [12]:
sales_fe = sales_fe.merge(
    order_summary,
    on='so_id',
    how='left'
)

print("New sales shape:", sales_fe.shape)

# Check
display(
    sales_fe[
        [
            'so_id',
            'order_quantity',
            'order_line_count',
            'order_sales_value',
            'unique_products'
        ]
    ].head()
)

New sales shape: (130402, 71)

,so_id,order_quantity,order_line_count,order_sales_value,unique_products
0,SO-990591,92,11,1720159.6,8
1,SO-990591,92,11,1720159.6,8
2,SO-990591,92,11,1720159.6,8
3,SO-990591,92,11,1720159.6,8
4,SO-990591,92,11,1720159.6,8

### **5. Average Selling Price**

Create the average selling price per order line.

In [17]:
sales_fe['average_unit_price'] = np.where(
    sales_fe['quantity'] > 0,
    sales_fe['line_total'] / sales_fe['quantity'],
    np.nan
)

display((sales_fe).head())

,so_id,line_number,product_id,quantity,unit_price,gst_rate,line_total,gst_amount,line_grand_total,customer_id,branch_id,order_date,delivery_date,order_status,payment_terms,total_order_value,total_gst_amount,grand_total,sales_channel,product_name,category,machine_type,brand,model_compatibility,unit_cost,unit_price_product,margin_percentage,gst_rate_product,weight_kg,dimensions_cm,material_type,warranty_months,reorder_level,safety_stock,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date,customer_type,industry_segment,city,state,pincode,region,branch_id_customer,credit_limit,current_balance,payment_terms_customer,customer_since,last_purchase_date_customer,total_purchase_value,customer_rating,order_year,order_month,order_month_name,order_quarter,order_week,order_day,order_day_name,order_day_of_week,calculated_line_total,line_total_difference,quantity_log,unit_price_log,order_quantity,order_line_count,order_sales_value,unique_products,average_unit_price
0,SO-990591,1,P018,19,11300,28,214700,60116.0,274816.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Wheel Rim WR-24,Undercarriage,Bulldozer,CAT,CAT D6R,8200,11300,37.8,28,24.00,70x25x25,steel,12,12,6,30,20,High,Medium,piece,8000,2024-02-20,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,214700,0,2.995732,9.332646,92,11,1720159.6,8,11300.0
1,SO-990591,2,P026,2,310,18,620,111.6,731.6,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,620,0,1.098612,5.739793,92,11,1720159.6,8,310.0
2,SO-990591,3,P026,3,310,18,930,167.4,1097.4,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,930,0,1.386294,5.739793,92,11,1720159.6,8,310.0
3,SO-990591,4,P013,9,1450,18,13050,2349.0,15399.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Seal Kit SK-15,Seals,Excavator,CAT,CAT 320D,950,1450,52.6,18,0.60,15x10x6,rubber,6,80,40,200,9,Medium,High,set,920,2022-12-19,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,13050,0,2.302585,7.280008,92,11,1720159.6,8,1450.0
4,SO-990591,5,P004,3,39800,28,119400,33432.0,152832.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Track Chain TC-45,Undercarriage,Bulldozer,Volvo,Volvo D6,32500,39800,22.5,28,210.00,180x40x35,steel,18,8,4,20,30,High,Low,set,32000,2020-06-18,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,119400,0,1.386294,10.591647,92,11,1720159.6,8,39800.0

### **6. GST Features**

In [20]:
# Create a GST Percentage if required
if 'gst_amount' in sales_fe.columns:

    sales_fe['gst_rate_calculated'] = np.where(
        sales_fe['line_total'] > 0,
        (
            sales_fe['gst_amount']
            / sales_fe['line_total']
        ) * 100,
        np.nan
    )

# Compare it with the existing GST rate:
if 'gst_rate' in sales_fe.columns:

    sales_fe['gst_rate_difference'] = (
        sales_fe['gst_rate_calculated']
        - sales_fe['gst_rate']
    )

    display(sales_fe.head())

,so_id,line_number,product_id,quantity,unit_price,gst_rate,line_total,gst_amount,line_grand_total,customer_id,branch_id,order_date,delivery_date,order_status,payment_terms,total_order_value,total_gst_amount,grand_total,sales_channel,product_name,category,machine_type,brand,model_compatibility,unit_cost,unit_price_product,margin_percentage,gst_rate_product,weight_kg,dimensions_cm,material_type,warranty_months,reorder_level,safety_stock,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date,customer_type,industry_segment,city,state,pincode,region,branch_id_customer,credit_limit,current_balance,payment_terms_customer,customer_since,last_purchase_date_customer,total_purchase_value,customer_rating,order_year,order_month,order_month_name,order_quarter,order_week,order_day,order_day_name,order_day_of_week,calculated_line_total,line_total_difference,quantity_log,unit_price_log,order_quantity,order_line_count,order_sales_value,unique_products,average_unit_price,gst_rate_calculated,gst_rate_difference
0,SO-990591,1,P018,19,11300,28,214700,60116.0,274816.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Wheel Rim WR-24,Undercarriage,Bulldozer,CAT,CAT D6R,8200,11300,37.8,28,24.00,70x25x25,steel,12,12,6,30,20,High,Medium,piece,8000,2024-02-20,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,214700,0,2.995732,9.332646,92,11,1720159.6,8,11300.0,28.0,3.552714e-15
1,SO-990591,2,P026,2,310,18,620,111.6,731.6,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,620,0,1.098612,5.739793,92,11,1720159.6,8,310.0,18.0,0.000000e+00
2,SO-990591,3,P026,3,310,18,930,167.4,1097.4,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,930,0,1.386294,5.739793,92,11,1720159.6,8,310.0,18.0,0.000000e+00
3,SO-990591,4,P013,9,1450,18,13050,2349.0,15399.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Seal Kit SK-15,Seals,Excavator,CAT,CAT 320D,950,1450,52.6,18,0.60,15x10x6,rubber,6,80,40,200,9,Medium,High,set,920,2022-12-19,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,13050,0,2.302585,7.280008,92,11,1720159.6,8,1450.0,18.0,0.000000e+00
4,SO-990591,5,P004,3,39800,28,119400,33432.0,152832.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Track Chain TC-45,Undercarriage,Bulldozer,Volvo,Volvo D6,32500,39800,22.5,28,210.00,180x40x35,steel,18,8,4,20,30,High,Low,set,32000,2020-06-18,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,119400,0,1.386294,10.591647,92,11,1720159.6,8,39800.0,28.0,3.552714e-15

### **6. Customer-Level Features**

Customer behaviour is useful for Week 3 analysis.

In [21]:
customer_summary = (
    sales_fe
    .groupby('customer_id')
    .agg(
        customer_total_sales=(
            'line_grand_total',
            'sum'
        ),
        customer_total_orders=(
            'so_id',
            'nunique'
        ),
        customer_total_quantity=(
            'quantity',
            'sum'
        ),
        customer_unique_products=(
            'product_id',
            'nunique'
        )
    )
    .reset_index()
)

display(customer_summary.head())

,customer_id,customer_total_sales,customer_total_orders,customer_total_quantity,customer_unique_products
0,C0001,67052288.0,40,2656,30
1,C0002,77917319.2,56,3636,30
2,C0003,50921823.2,40,2365,30
3,C0004,62484367.6,47,2995,30
4,C0005,85668379.8,51,3747,30

Add Customer Features

In [22]:
sales_fe = sales_fe.merge(
    customer_summary,
    on='customer_id',
    how='left'
)

print("Sales shape:", sales_fe.shape)

Sales shape: (130402, 78)

### **7. Product-Level Features**

In [23]:
product_summary = (
    sales_fe
    .groupby('product_id')
    .agg(
        product_total_sales=(
            'line_grand_total',
            'sum'
        ),
        product_total_quantity=(
            'quantity',
            'sum'
        ),
        product_total_orders=(
            'so_id',
            'nunique'
        ),
        product_unique_customers=(
            'customer_id',
            'nunique'
        )
    )
    .reset_index()
)

display(product_summary.head())

,product_id,product_total_sales,product_total_quantity,product_total_orders,product_unique_customers
0,P001,1.423399e+09,45389,3854,500
1,P002,3.852256e+07,45342,3861,500
2,P003,6.738390e+07,45684,3895,500
3,P004,2.321773e+09,45575,3781,500
4,P005,4.870012e+08,45026,3840,500

Add product features

In [24]:
sales_fe = sales_fe.merge(
    product_summary,
    on='product_id',
    how='left'
)

print("Sales shape:", sales_fe.shape)

Sales shape: (130402, 82)

### **8. Branch-Level Features**

In [25]:
if 'branch_id' in sales_fe.columns:

    branch_summary = (
        sales_fe
        .groupby('branch_id')
        .agg(
            branch_total_sales=(
                'line_grand_total',
                'sum'
            ),
            branch_total_orders=(
                'so_id',
                'nunique'
            ),
            branch_total_quantity=(
                'quantity',
                'sum'
            )
        )
        .reset_index()
    )

    display(branch_summary.head())

  branch_id  branch_total_sales  branch_total_orders  branch_total_quantity
0    AHM001        5.616586e+09                 3446                 236347
1    CHN001        6.615942e+09                 4067                 280446
2    DEL001        4.926515e+09                 2953                 204734
3    HYD001        4.398510e+09                 2768                 189163
4    KOL001        6.100494e+09                 3794                 256095

### **9. Sales Channel Features**

In [26]:
if 'sales_channel' in sales_fe.columns:

    channel_summary = (
        sales_fe
        .groupby('sales_channel')
        .agg(
            channel_total_sales=(
                'line_grand_total',
                'sum'
            ),
            channel_total_orders=(
                'so_id',
                'nunique'
            ),
            channel_total_quantity=(
                'quantity',
                'sum'
            )
        )
        .reset_index()
    )

    display(channel_summary)

,sales_channel,channel_total_sales,channel_total_orders,channel_total_quantity
0,Counter Sale,8.172855e+09,5014,345148
1,Dealer Network,8.107783e+09,5028,342006
2,Field Sales,8.210171e+09,5036,346107
3,Online,7.933945e+09,4922,335273

### **10. Order Value Categories**

In [27]:
order_summary['order_value_category'] = pd.cut(
    order_summary['order_sales_value'],
    bins=[
        -np.inf,
        1000,
        5000,
        10000,
        50000,
        np.inf
    ],
    labels=[
        'Very Low',
        'Low',
        'Medium',
        'High',
        'Very High'
    ]
)

display(
    order_summary[
        [
            'so_id',
            'order_sales_value',
            'order_value_category'
        ]
    ].head(10)
)

       so_id  order_sales_value order_value_category
0  SO-100070           292352.0            Very High
1  SO-100088          2770123.8            Very High
2  SO-100155          1564183.0            Very High
3  SO-100192           264196.0            Very High
4  SO-100220           168070.8            Very High
5  SO-100241          2563943.0            Very High
6  SO-100259          2013088.6            Very High
7  SO-100281            26915.8                 High
8  SO-100340          2670336.0            Very High
9  SO-100355          5854806.0            Very High

These thresholds are analytical categories, so you can adjust them after examining your actual sales distribution.

### **11. Customer Recency Feature**

In [29]:
# If the dataset contains last_purchase_date, convert it first.

if 'last_purchase_date' in sales_fe.columns:

    sales_fe['last_purchase_date'] = pd.to_datetime(
        sales_fe['last_purchase_date'],
        errors='coerce'
    )
# Then calculate recency based on the latest order date in the dataset:
if 'last_purchase_date' in sales_fe.columns:

    analysis_date = sales_fe['order_date'].max()

    sales_fe['customer_recency_days'] = (
        analysis_date
        - sales_fe['last_purchase_date']
    ).dt.days

### **12. Check Engineered Features**

In [30]:
print("Final shape:", sales_fe.shape)

print("\nNew columns:")

original_columns = set(sales.columns)

new_columns = [
    col
    for col in sales_fe.columns
    if col not in original_columns
]

print(new_columns)

Final shape: (130402, 83)

New columns:
['order_year', 'order_month', 'order_month_name', 'order_quarter', 'order_week', 'order_day', 'order_day_name', 'order_day_of_week', 'calculated_line_total', 'line_total_difference', 'quantity_log', 'unit_price_log', 'order_quantity', 'order_line_count', 'order_sales_value', 'unique_products', 'average_unit_price', 'gst_rate_calculated', 'gst_rate_difference', 'customer_total_sales', 'customer_total_orders', 'customer_total_quantity', 'customer_unique_products', 'product_total_sales', 'product_total_quantity', 'product_total_orders', 'product_unique_customers', 'customer_recency_days']

### **13. Check Missing Values**

In [31]:
feature_missing = (
    sales_fe[new_columns]
    .isnull()
    .sum()
    .sort_values(ascending=False)
)

display(feature_missing)

order_year                  0
order_month                 0
order_month_name            0
order_quarter               0
order_week                  0
order_day                   0
order_day_name              0
order_day_of_week           0
calculated_line_total       0
line_total_difference       0
quantity_log                0
unit_price_log              0
order_quantity              0
order_line_count            0
order_sales_value           0
unique_products             0
average_unit_price          0
gst_rate_calculated         0
gst_rate_difference         0
customer_total_sales        0
customer_total_orders       0
customer_total_quantity     0
customer_unique_products    0
product_total_sales         0
product_total_quantity      0
product_total_orders        0
product_unique_customers    0
customer_recency_days       0
dtype: int64

### **14. Check Duplicate Records**

In [33]:
print(
    "Duplicate rows:",
    sales_fe.duplicated().sum()
)

# Check the Sales Line identity
line_columns = [
    col for col in [
        'so_id',
        'line_number',
        'product_id'
    ]
    if col in sales_fe.columns
]

if line_columns:
    print(
        "Duplicate sales lines:",
        sales_fe.duplicated(
            subset=line_columns
        ).sum()
    )

Duplicate rows: 0
Duplicate sales lines: 0

### **15. Feature Summary**

In [34]:
feature_summary = pd.DataFrame({
    'feature': new_columns,
    'data_type': [
        sales_fe[col].dtype
        for col in new_columns
    ],
    'missing_values': [
        sales_fe[col].isna().sum()
        for col in new_columns
    ],
    'unique_values': [
        sales_fe[col].nunique()
        for col in new_columns
    ]
})

display(feature_summary)

                     feature data_type  missing_values  unique_values
0                 order_year     int32               0              6
1                order_month     int32               0             12
2           order_month_name    object               0             12
3              order_quarter     int32               0              4
4                 order_week    UInt32               0             53
5                  order_day     int32               0             31
6             order_day_name    object               0              7
7          order_day_of_week     int32               0              7
8      calculated_line_total     int64               0            534
9      line_total_difference     int64               0              1
10              quantity_log   float64               0             20
11            unit_price_log   float64               0             28
12            order_quantity     int64               0            179
13          order_line_count     int64               0             12
14         order_sales_value   float64               0          18735
15           unique_products     int64               0             12
16        average_unit_price   float64               0             28
17       gst_rate_calculated   float64               0              4
18       gst_rate_difference   float64               0              3
19      customer_total_sales   float64               0            500
20     customer_total_orders     int64               0             35
21   customer_total_quantity     int64               0            433
22  customer_unique_products     int64               0              2
23       product_total_sales   float64               0             30
24    product_total_quantity     int64               0             30
25      product_total_orders     int64               0             28
26  product_unique_customers     int64               0              2
27     customer_recency_days     int64               0             30

### **16. Final Dataset Preview**

In [35]:
display(
    sales_fe.head()
)

,so_id,line_number,product_id,quantity,unit_price,gst_rate,line_total,gst_amount,line_grand_total,customer_id,branch_id,order_date,delivery_date,order_status,payment_terms,total_order_value,total_gst_amount,grand_total,sales_channel,product_name,category,machine_type,brand,model_compatibility,unit_cost,unit_price_product,margin_percentage,gst_rate_product,weight_kg,dimensions_cm,material_type,warranty_months,reorder_level,safety_stock,max_stock_level,lead_time_days,criticality_level,usage_frequency,uom,last_purchase_price,last_purchase_date,customer_type,industry_segment,city,state,pincode,region,branch_id_customer,credit_limit,current_balance,payment_terms_customer,customer_since,last_purchase_date_customer,total_purchase_value,customer_rating,order_year,order_month,order_month_name,order_quarter,order_week,order_day,order_day_name,order_day_of_week,calculated_line_total,line_total_difference,quantity_log,unit_price_log,order_quantity,order_line_count,order_sales_value,unique_products,average_unit_price,gst_rate_calculated,gst_rate_difference,customer_total_sales,customer_total_orders,customer_total_quantity,customer_unique_products,product_total_sales,product_total_quantity,product_total_orders,product_unique_customers,customer_recency_days
0,SO-990591,1,P018,19,11300,28,214700,60116.0,274816.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Wheel Rim WR-24,Undercarriage,Bulldozer,CAT,CAT D6R,8200,11300,37.8,28,24.00,70x25x25,steel,12,12,6,30,20,High,Medium,piece,8000,2024-02-20,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,214700,0,2.995732,9.332646,92,11,1720159.6,8,11300.0,28.0,3.552714e-15,87747724.2,48,3393,30,6.512705e+08,45027,3839,500,315
1,SO-990591,2,P026,2,310,18,620,111.6,731.6,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,620,0,1.098612,5.739793,92,11,1720159.6,8,310.0,18.0,0.000000e+00,87747724.2,48,3393,30,1.640394e+07,44844,3823,500,1734
2,SO-990591,3,P026,3,310,18,930,167.4,1097.4,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Grease Cartridge GC-5,Lubricants,All,Generic,All Models,180,310,72.2,18,0.45,25x6x6,synthetic,3,200,100,500,4,Low,High,cartridge,170,2020-04-02,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,930,0,1.386294,5.739793,92,11,1720159.6,8,310.0,18.0,0.000000e+00,87747724.2,48,3393,30,1.640394e+07,44844,3823,500,1734
3,SO-990591,4,P013,9,1450,18,13050,2349.0,15399.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Seal Kit SK-15,Seals,Excavator,CAT,CAT 320D,950,1450,52.6,18,0.60,15x10x6,rubber,6,80,40,200,9,Medium,High,set,920,2022-12-19,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,13050,0,2.302585,7.280008,92,11,1720159.6,8,1450.0,18.0,0.000000e+00,87747724.2,48,3393,30,7.542259e+07,44081,3783,499,743
4,SO-990591,5,P004,3,39800,28,119400,33432.0,152832.0,C0070,AHM001,2022-05-24,2022-05-28,Delivered,Net 30,1345720,374439.6,1720159.6,Counter Sale,Track Chain TC-45,Undercarriage,Bulldozer,Volvo,Volvo D6,32500,39800,22.5,28,210.00,180x40x35,steel,18,8,4,20,30,High,Low,set,32000,2020-06-18,Government,Logistics,Ahmedabad,Gujarat,784913,West,AHM001,549454,84153,Net 30,2022-11-10,2024-12-04,4644233,3,2022,5,May,2,21,24,Tuesday,1,119400,0,1.386294,10.591647,92,11,1720159.6,8,39800.0,28.0,3.552714e-15,87747724.2,48,3393,30,2.321773e+09,45575,3781,500,1657

### **Final Feature Engineering Report**

In [36]:
print("=" * 60)
print("WEEK 3 – FEATURE ENGINEERING SUMMARY")
print("=" * 60)

print("\nOriginal Sales Shape:")
print(sales.shape)

print("\nFeature-Engineered Sales Shape:")
print(sales_fe.shape)

print("\nNumber of New Features:")
print(len(new_columns))

print("\nNew Features:")
for feature in new_columns:
    print("-", feature)

print("\nDuplicate Rows:")
print(sales_fe.duplicated().sum())

print("\nFeature Engineering Completed Successfully.")

============================================================
WEEK 3 – FEATURE ENGINEERING SUMMARY
============================================================

Original Sales Shape:
(130402, 55)

Feature-Engineered Sales Shape:
(130402, 83)

Number of New Features:
28

New Features:
- order_year
- order_month
- order_month_name
- order_quarter
- order_week
- order_day
- order_day_name
- order_day_of_week
- calculated_line_total
- line_total_difference
- quantity_log
- unit_price_log
- order_quantity
- order_line_count
- order_sales_value
- unique_products
- average_unit_price
- gst_rate_calculated
- gst_rate_difference
- customer_total_sales
- customer_total_orders
- customer_total_quantity
- customer_unique_products
- product_total_sales
- product_total_quantity
- product_total_orders
- product_unique_customers
- customer_recency_days

Duplicate Rows:
0

Feature Engineering Completed Successfully.

Save feature engineering datasets.

In [37]:
import os

os.makedirs(
    "../week-03/features",
    exist_ok=True
)

sales_fe.to_csv(
    "../week-03/features/sales_features.csv",
    index=False
)

print("Feature-engineered sales dataset saved successfully.")

Feature-engineered sales dataset saved successfully.

Save Supporting Tables.

In [38]:
order_summary.to_csv(
    "../week-03/features/order_features.csv",
    index=False
)

customer_summary.to_csv(
    "../week-03/features/customer_features.csv",
    index=False
)

product_summary.to_csv(
    "../week-03/features/product_features.csv",
    index=False
)

print("Supporting feature tables saved successfully.")

Supporting feature tables saved successfully.